# Tautan ini akan memunculkan tombol 'Sponsor' di repositori Anda
# Anda bisa membuka komentar (#) untuk mengaktifkan platform tambahan

github: [aibersemi]
# patreon: username-patreon
# open_collective: username-open-collective
# ko_fi: username-kofi
# buy_me_a_coffee: username-bmac
custom: ["https://saweria.co/aibersemi"]
